clear

myfile{1,1}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_NOTITER_Nd=5_Nl=1_PhiD=60_gL2=1000.mat';
myfile{1,2}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_ILMI_Nd=5_Nl=1_PhiD=60_gL2=1000.mat';

myfile{2,1}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_NOTITER_Nd=5_Nl=1_PhiD=60_gL2=100.mat';
myfile{2,2}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_ILMI_Nd=5_Nl=1_PhiD=60_gL2=100.mat';

myfile{3,1}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_NOTITER_Nd=5_Nl=1_PhiD=60_gL2=10.mat';
myfile{3,2}='cases\WoodBerry\lmilab\results\data\lmilab_exWB_SOFS_L2N_ILMI_Nd=5_Nl=1_PhiD=60_gL2=10.mat';

tstart=0; tend=300; tstep=0.1; t=(tstart:tstep:tend)'; %time domain
yf=[0.1;0.1]; dw=0.245;

Nrlt=0;
save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat');
while Nrlt<length(myfile)
    rlt(Nrlt+1).data=myfile{Nrlt+1,1};
    load(myfile{Nrlt+1,1},...
        'gL2','PhiD','Nx','Ny', ...
        'KPpi','KIpi','TIpi','alppi','elapsedTime_pi',...
        'A_pi','Bu_pi','Bw_pi','Cy_pi');
    rlt(Nrlt+1).gL2=gL2;
    rlt(Nrlt+1).PhiD=nthroot(det(PhiD),Ny);
%--------------------------------------------------------------------------
%----- This work technique PI control -------------------------------------
    rlt(Nrlt+1).TW.PI.KP=[];
    rlt(Nrlt+1).TW.PI.KI=[];
    rlt(Nrlt+1).TW.PI.TI=[];
    rlt(Nrlt+1).TW.PI.alp=[];
    rlt(Nrlt+1).TW.PI.ElapTime=[];
    
    rlt(Nrlt+1).TW.PI.Gload=[];
    rlt(Nrlt+1).TW.PI.Gsp=[];
    rlt(Nrlt+1).TW.PI.eig=[];
    rlt(Nrlt+1).TW.PI.hinf=[];
    rlt(Nrlt+1).TW.PI.info=[];
    
    if ~isempty(alppi)
    rlt(Nrlt+1).TW.PI.KP=KPpi;
    rlt(Nrlt+1).TW.PI.KI=KIpi;
    rlt(Nrlt+1).TW.PI.TI=TIpi;
    rlt(Nrlt+1).TW.PI.alp=alppi;
    rlt(Nrlt+1).TW.PI.ElapTime=elapsedTime_pi;
    
    K_=[KPpi,KIpi];
    rlt(Nrlt+1).TW.PI.Gload=ss(A_pi-Bu_pi*K_*Cy_pi, Bw_pi, Cy_pi(1:Ny,:), 0);
    Br_pi=[Bu_pi(1:Nx,:)*KPpi;-eye(Ny)];
    rlt(Nrlt+1).TW.PI.Gsp=ss(A_pi-Bu_pi*K_*Cy_pi, Br_pi, Cy_pi(1:Ny,:), 0);
    rlt(Nrlt+1).TW.PI.eig=eig(rlt(Nrlt+1).TW.PI.Gload);
    rlt(Nrlt+1).TW.PI.hinf=hinfnorm(rlt(Nrlt+1).TW.PI.Gload);
    rlt(Nrlt+1).TW.PI.info=stepinfo_caseWB(KPpi,KIpi,[],[],ss(A_pi,[Bu_pi,Bw_pi],Cy_pi,0),t,[yf;dw],'PI');
    end
%--------------------------------------------------------------------------
%----- This work technique PID control ------------------------------------
    load(myfile{Nrlt+1,1},...
        'PhiD','Nx','Ny', ...
        'KPpid','KIpid','TIpid','KDpid','TDpid','alppid','elapsedTime_pid',...
        'A_pid','Bu_pid','Bw_pid','Cy_pid');

    rlt(Nrlt+1).TW.PID.KP=[];
    rlt(Nrlt+1).TW.PID.KI=[];
    rlt(Nrlt+1).TW.PID.TI=[];
    rlt(Nrlt+1).TW.PID.KD=[];
    rlt(Nrlt+1).TW.PID.TD=[];
    rlt(Nrlt+1).TW.PID.alp=[];
    rlt(Nrlt+1).TW.PID.ElapTime=[];
    
    rlt(Nrlt+1).TW.PID.Gload=[];
    rlt(Nrlt+1).TW.PID.Gsp=[];
    rlt(Nrlt+1).TW.PID.eig=[];
    rlt(Nrlt+1).TW.PID.hinf=[];
    rlt(Nrlt+1).TW.PID.info=[];
    
    if ~isempty(alppid)
    rlt(Nrlt+1).TW.PID.KP=KPpid;
    rlt(Nrlt+1).TW.PID.KI=KIpid;
    rlt(Nrlt+1).TW.PID.TI=TIpid;
    rlt(Nrlt+1).TW.PID.KD=KDpid;
    rlt(Nrlt+1).TW.PID.TD=TDpid;
    rlt(Nrlt+1).TW.PID.alp=alppid;
    rlt(Nrlt+1).TW.PID.ElapTime=elapsedTime_pid;
    
    K_=[KPpid,KIpid,KDpid];
    rlt(Nrlt+1).TW.PID.Gload=ss(A_pid-Bu_pid*K_*Cy_pid, Bw_pid, Cy_pid(1:Ny,:), 0);
    Br_pid=[Bu_pid(1:Nx,:)*KPpid;-eye(Ny);-PhiD*Cy_pid(1:Ny,1:Nx)*Bu_pid(1:Nx,:)*KPpid];
    rlt(Nrlt+1).TW.PID.Gsp=ss(A_pid-Bu_pid*K_*Cy_pid, Br_pid, Cy_pid(1:Ny,:), 0);
    rlt(Nrlt+1).TW.PID.eig=eig(rlt(Nrlt+1).TW.PID.Gload);
    rlt(Nrlt+1).TW.PID.hinf=hinfnorm(rlt(Nrlt+1).TW.PID.Gload);
    rlt(Nrlt+1).TW.PID.info=stepinfo_caseWB(KPpid,KIpid,KDpid,PhiD,ss(A_pid,[Bu_pid,Bw_pid],Cy_pid,0),t,[yf;dw],'PID');
    end
%--------------------------------------------------------------------------
%----- ILMI technique PI control ------------------------------------------
load(myfile{Nrlt+1,2},...
        'Nx','Ny', ...
        'KPpi_ILMI','KIpi_ILMI','TIpi_ILMI','alppi_ILMI','elapsedTime_pi_ILMI','iterpi_ILMI',...
        'A_pi','Bu_pi','Bw_pi','Cy_pi');

    rlt(Nrlt+1).ILMI.PI.KP=[];
    rlt(Nrlt+1).ILMI.PI.KI=[];
    rlt(Nrlt+1).ILMI.PI.TI=[];
    rlt(Nrlt+1).ILMI.PI.alp=[];
    rlt(Nrlt+1).ILMI.PI.iter=[];
    rlt(Nrlt+1).ILMI.PI.ElapTime=[];
    
    rlt(Nrlt+1).ILMI.PI.Gload=[];
    rlt(Nrlt+1).ILMI.PI.Gsp=[];
    rlt(Nrlt+1).ILMI.PI.eig=[];
    rlt(Nrlt+1).ILMI.PI.hinf=[];
    rlt(Nrlt+1).ILMI.PI.info=[];
    
    if ~isempty(alppi_ILMI)
    rlt(Nrlt+1).ILMI.PI.KP=KPpi_ILMI;
    rlt(Nrlt+1).ILMI.PI.KI=KIpi_ILMI;
    rlt(Nrlt+1).ILMI.PI.TI=TIpi_ILMI;
    rlt(Nrlt+1).ILMI.PI.alp=alppi_ILMI;
    rlt(Nrlt+1).ILMI.PI.iter=iterpi_ILMI;
    rlt(Nrlt+1).ILMI.PI.ElapTime=elapsedTime_pi_ILMI;
    
    K_=[KPpi_ILMI,KIpi_ILMI];
    rlt(Nrlt+1).ILMI.PI.Gload=ss(A_pi-Bu_pi*K_*Cy_pi, Bw_pi, Cy_pi(1:Ny,:), 0);
    Br_pi_ILMI=[Bu_pi(1:Nx,:)*KPpi_ILMI;-eye(Ny)];
    rlt(Nrlt+1).ILMI.PI.Gsp=ss(A_pi-Bu_pi*K_*Cy_pi, Br_pi_ILMI, Cy_pi(1:Ny,:), 0);
    rlt(Nrlt+1).ILMI.PI.eig=eig(rlt(Nrlt+1).ILMI.PI.Gload);
    rlt(Nrlt+1).ILMI.PI.hinf=hinfnorm(rlt(Nrlt+1).ILMI.PI.Gload);
    rlt(Nrlt+1).ILMI.PI.info=stepinfo_caseWB(KPpi_ILMI,KIpi_ILMI,[],[],ss(A_pi,[Bu_pi,Bw_pi],Cy_pi,0),t,[yf;dw],'PI');
    end
%--------------------------------------------------------------------------
%----- ILMI technique PID control -----------------------------------------
    load(myfile{Nrlt+1,2},...
        'PhiD','Nx','Ny', ...
        'KPpid_ILMI','KIpid_ILMI','TIpid_ILMI','KDpid_ILMI','TDpid_ILMI','alppid_ILMI','elapsedTime_pid_ILMI','iterpid_ILMI',...
        'A_pid','Bu_pid','Bw_pid','Cy_pid');

    rlt(Nrlt+1).ILMI.PID.KP=[];
    rlt(Nrlt+1).ILMI.PID.KI=[];
    rlt(Nrlt+1).ILMI.PID.TI=[];
    rlt(Nrlt+1).ILMI.PID.KD=[];
    rlt(Nrlt+1).ILMI.PID.TD=[];
    rlt(Nrlt+1).ILMI.PID.alp=[];
    rlt(Nrlt+1).ILMI.PID.iter=[];
    rlt(Nrlt+1).ILMI.PID.ElapTime=[];
    
    rlt(Nrlt+1).ILMI.PID.Gload=[];
    rlt(Nrlt+1).ILMI.PID.Gsp=[];
    rlt(Nrlt+1).ILMI.PID.eig=[];
    rlt(Nrlt+1).ILMI.PID.hinf=[];
    rlt(Nrlt+1).ILMI.PID.info=[];
    
    if ~isempty(alppid_ILMI)
    rlt(Nrlt+1).ILMI.PID.KP=KPpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.KI=KIpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.TI=TIpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.KD=KDpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.TD=TDpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.alp=alppid_ILMI;
    rlt(Nrlt+1).ILMI.PID.iter=iterpid_ILMI;
    rlt(Nrlt+1).ILMI.PID.ElapTime=elapsedTime_pid_ILMI;
    
    
    K_=[KPpid_ILMI,KIpid_ILMI,KDpid_ILMI];
    rlt(Nrlt+1).ILMI.PID.Gload=ss(A_pid-Bu_pid*K_*Cy_pid, Bw_pid, Cy_pid(1:Ny,:), 0);
    Br_pid_ILMI=[Bu_pid(1:Nx,:)*KPpid_ILMI;-eye(Ny);-PhiD*Cy_pid(1:Ny,1:Nx)*Bu_pid(1:Nx,:)*KPpid_ILMI];
    rlt(Nrlt+1).ILMI.PID.Gsp=ss(A_pid-Bu_pid*K_*Cy_pid, Br_pid_ILMI, Cy_pid(1:Ny,:), 0);
    rlt(Nrlt+1).ILMI.PID.eig=eig(rlt(Nrlt+1).ILMI.PID.Gload);
    rlt(Nrlt+1).ILMI.PID.hinf=hinfnorm(rlt(Nrlt+1).ILMI.PID.Gload);
    rlt(Nrlt+1).ILMI.PID.info=stepinfo_caseWB(KPpid_ILMI,KIpid_ILMI,KDpid_ILMI,PhiD,ss(A_pid,[Bu_pid,Bw_pid],Cy_pid,0),t,[yf;dw],'PID');
    end
    %--------------------------------------------------------------------------
    
    Nrlt=Nrlt+1;
    save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','rlt','-append');
    load('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','myfile');
end

%Reload results
clear
load('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','rlt');

%Disp tables
% ----- Table 1 -----------------------------------------------------------
tab1=table(...
    num2str([rlt(1).TW.PI.KP(1,1);  rlt(1).TW.PI.KP(2,2);  rlt(1).ILMI.PI.KP(1,1);  rlt(1).ILMI.PI.KP(2,2);...
             rlt(2).TW.PI.KP(1,1);  rlt(2).TW.PI.KP(2,2);  rlt(2).ILMI.PI.KP(1,1);  rlt(2).ILMI.PI.KP(2,2);...
             rlt(3).TW.PI.KP(1,1);  rlt(3).TW.PI.KP(2,2);  rlt(3).ILMI.PI.KP(1,1);  rlt(3).ILMI.PI.KP(2,2)],'%.4f'),...
    num2str([rlt(1).TW.PI.TI(1,1);  rlt(1).TW.PI.TI(2,2);  rlt(1).ILMI.PI.TI(1,1);  rlt(1).ILMI.PI.TI(2,2);...
             rlt(2).TW.PI.TI(1,1);  rlt(2).TW.PI.TI(2,2);  rlt(2).ILMI.PI.TI(1,1);  rlt(2).ILMI.PI.TI(2,2);...
             rlt(3).TW.PI.TI(1,1);  rlt(3).TW.PI.TI(2,2);  rlt(3).ILMI.PI.TI(1,1);  rlt(3).ILMI.PI.TI(2,2)],'%.2f'),...
    num2str([rlt(1).TW.PI.alp;      rlt(1).TW.PI.alp;      rlt(1).ILMI.PI.alp;      rlt(1).ILMI.PI.alp;...
             rlt(2).TW.PI.alp;      rlt(2).TW.PI.alp;      rlt(2).ILMI.PI.alp;      rlt(2).ILMI.PI.alp;...
             rlt(3).TW.PI.alp;      rlt(3).TW.PI.alp;      rlt(3).ILMI.PI.alp;      rlt(3).ILMI.PI.alp],'%.4f'), ... 
    num2str([rlt(1).TW.PI.ElapTime; rlt(1).TW.PI.ElapTime; rlt(1).ILMI.PI.ElapTime; rlt(1).ILMI.PI.ElapTime;...
             rlt(2).TW.PI.ElapTime; rlt(2).TW.PI.ElapTime; rlt(2).ILMI.PI.ElapTime; rlt(2).ILMI.PI.ElapTime; ...
             rlt(3).TW.PI.ElapTime; rlt(3).TW.PI.ElapTime; rlt(3).ILMI.PI.ElapTime; rlt(3).ILMI.PI.ElapTime],'%.1f'),...
    num2str([rlt(1).TW.PI.hinf;     rlt(1).TW.PI.hinf;     rlt(1).ILMI.PI.hinf;     rlt(1).ILMI.PI.hinf;...
             rlt(2).TW.PI.hinf;     rlt(2).TW.PI.hinf;     rlt(2).ILMI.PI.hinf;     rlt(2).ILMI.PI.hinf;...
             rlt(3).TW.PI.hinf;     rlt(3).TW.PI.hinf;     rlt(3).ILMI.PI.hinf;     rlt(3).ILMI.PI.hinf],'%.4f'),...
    [1; 1; 2; 2;...
     3; 3; 4; 4;...
     5; 5; 6; 6]...
    );
tab1.Properties.RowNames={...
    '10^3 TW r-w_D',...
    '10^3 TW v-w_B',...
    '10^3 ILMI r-w_D',...
    '10^3 ILMI v-w_B',...
    '10^2 TW r-w_D',...
    '10^2 TW v-w_B',...
    '10^2 ILMI r-w_D',...
    '10^2 ILMI v-w_B',...
    '10 TW r-w_D',...
    '10 TW v-w_B',...
    '10 ILMI r-w_D',...
    '10 ILMI v-w_B'};
tab1.Properties.VariableNames={'K_P','T_I','alp^*','Comp. time [s]','|G_{load}|_\infty','#'};
tab1
save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','tab1','-append');
%--------------------------------------------------------------------------
% ----- Table 2 -----------------------------------------------------------
tab2=table(...
    num2str([rlt(1).TW.PID.KP(1,1);  rlt(1).TW.PID.KP(2,2);  rlt(1).ILMI.PID.KP(1,1);  rlt(1).ILMI.PID.KP(2,2);...
             rlt(2).TW.PID.KP(1,1);  rlt(2).TW.PID.KP(2,2);  rlt(2).ILMI.PID.KP(1,1);  rlt(2).ILMI.PID.KP(2,2);...
             rlt(3).TW.PID.KP(1,1);  rlt(3).TW.PID.KP(2,2);  rlt(3).ILMI.PID.KP(1,1);  rlt(3).ILMI.PID.KP(2,2)],'%.4f'),...
    num2str([rlt(1).TW.PID.TI(1,1);  rlt(1).TW.PID.TI(2,2);  rlt(1).ILMI.PID.TI(1,1);  rlt(1).ILMI.PID.TI(2,2);...
             rlt(2).TW.PID.TI(1,1);  rlt(2).TW.PID.TI(2,2);  rlt(2).ILMI.PID.TI(1,1);  rlt(2).ILMI.PID.TI(2,2);...
             rlt(3).TW.PID.TI(1,1);  rlt(3).TW.PID.TI(2,2);  rlt(3).ILMI.PID.TI(1,1);  rlt(3).ILMI.PID.TI(2,2)],'%.2f'),...
    num2str([rlt(1).TW.PID.TD(1,1);  rlt(1).TW.PID.TD(2,2);  rlt(1).ILMI.PID.TD(1,1);  rlt(1).ILMI.PID.TD(2,2);...
             rlt(2).TW.PID.TD(1,1);  rlt(2).TW.PID.TD(2,2);  rlt(2).ILMI.PID.TD(1,1);  rlt(2).ILMI.PID.TD(2,2);...
             rlt(3).TW.PID.TD(1,1);  rlt(3).TW.PID.TD(2,2);  rlt(3).ILMI.PID.TD(1,1);  rlt(3).ILMI.PID.TD(2,2)],'%.2f'),...             
    num2str([rlt(1).TW.PID.alp;      rlt(1).TW.PID.alp;      rlt(1).ILMI.PID.alp;      rlt(1).ILMI.PID.alp;...
             rlt(2).TW.PID.alp;      rlt(2).TW.PID.alp;      rlt(2).ILMI.PID.alp;      rlt(2).ILMI.PID.alp;...
             rlt(3).TW.PID.alp;      rlt(3).TW.PID.alp;      rlt(3).ILMI.PID.alp;      rlt(3).ILMI.PID.alp],'%.4f'), ... 
    num2str([rlt(1).TW.PID.ElapTime; rlt(1).TW.PID.ElapTime; rlt(1).ILMI.PID.ElapTime; rlt(1).ILMI.PID.ElapTime;...
             rlt(2).TW.PID.ElapTime; rlt(2).TW.PID.ElapTime; rlt(2).ILMI.PID.ElapTime; rlt(2).ILMI.PID.ElapTime; ...
             rlt(3).TW.PID.ElapTime; rlt(3).TW.PID.ElapTime; rlt(3).ILMI.PID.ElapTime; rlt(3).ILMI.PID.ElapTime],'%.1f'),...
    num2str([rlt(1).TW.PID.hinf;     rlt(1).TW.PID.hinf;     rlt(1).ILMI.PID.hinf;     rlt(1).ILMI.PID.hinf;...
             rlt(2).TW.PID.hinf;     rlt(2).TW.PID.hinf;     rlt(2).ILMI.PID.hinf;     rlt(2).ILMI.PID.hinf;...
             rlt(3).TW.PID.hinf;     rlt(3).TW.PID.hinf;     rlt(3).ILMI.PID.hinf;     rlt(3).ILMI.PID.hinf],'%.4f'),...
    [7; 7; 8; 8;...
     9; 9; 10; 10;...
     11; 11; 12; 12]...
    );
tab2.Properties.RowNames={...
    '10^3 TW r-w_D',...
    '10^3 TW v-w_B',...
    '10^3 ILMI r-w_D',...
    '10^3 ILMI v-w_B',...
    '10^2 TW r-w_D',...
    '10^2 TW v-w_B',...
    '10^2 ILMI r-w_D',...
    '10^2 ILMI v-w_B',...
    '10 TW r-w_D',...
    '10 TW v-w_B',...
    '10 ILMI r-w_D',...
    '10 ILMI v-w_B'};
tab2.Properties.VariableNames={'K_P','T_I','T_D','alp^*','Comp. time [s]','|G_{load}|_\infty','#'};
tab2
save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','tab2','-append');
%--------------------------------------------------------------------------
% ----- Table 3 -----------------------------------------------------------
tab3=table(...
    num2str([rlt(1).TW.PI.info(1,1).ITAE;           rlt(1).TW.PI.info(2,1).ITAE;           rlt(1).ILMI.PI.info(1,1).ITAE;           rlt(1).ILMI.PI.info(2,1).ITAE;...
             rlt(2).TW.PI.info(1,1).ITAE;           rlt(2).TW.PI.info(2,1).ITAE;           rlt(2).ILMI.PI.info(1,1).ITAE;           rlt(2).ILMI.PI.info(2,1).ITAE;...
             rlt(3).TW.PI.info(1,1).ITAE;           rlt(3).TW.PI.info(2,1).ITAE;           rlt(3).ILMI.PI.info(1,1).ITAE;           rlt(3).ILMI.PI.info(2,1).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PI.info(1,2).ITAE;           rlt(1).TW.PI.info(2,2).ITAE;           rlt(1).ILMI.PI.info(1,2).ITAE;           rlt(1).ILMI.PI.info(2,2).ITAE;...
             rlt(2).TW.PI.info(1,2).ITAE;           rlt(2).TW.PI.info(2,2).ITAE;           rlt(2).ILMI.PI.info(1,2).ITAE;           rlt(2).ILMI.PI.info(2,2).ITAE;...
             rlt(3).TW.PI.info(1,2).ITAE;           rlt(3).TW.PI.info(2,2).ITAE;           rlt(3).ILMI.PI.info(1,2).ITAE;           rlt(3).ILMI.PI.info(2,2).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PI.info(1,3).ITAE;           rlt(1).TW.PI.info(2,3).ITAE;           rlt(1).ILMI.PI.info(1,3).ITAE;           rlt(1).ILMI.PI.info(2,3).ITAE;...
             rlt(2).TW.PI.info(1,3).ITAE;           rlt(2).TW.PI.info(2,3).ITAE;           rlt(2).ILMI.PI.info(1,3).ITAE;           rlt(2).ILMI.PI.info(2,3).ITAE;...
             rlt(3).TW.PI.info(1,3).ITAE;           rlt(3).TW.PI.info(2,3).ITAE;           rlt(3).ILMI.PI.info(1,3).ITAE;           rlt(3).ILMI.PI.info(2,3).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PI.info(1,1).TransientTime;  rlt(1).TW.PI.info(2,1).TransientTime;  rlt(1).ILMI.PI.info(1,1).TransientTime;  rlt(1).ILMI.PI.info(2,1).TransientTime;...
             rlt(2).TW.PI.info(1,1).TransientTime;  rlt(2).TW.PI.info(2,1).TransientTime;  rlt(2).ILMI.PI.info(1,1).TransientTime;  rlt(2).ILMI.PI.info(2,1).TransientTime;...
             rlt(3).TW.PI.info(1,1).TransientTime;  rlt(3).TW.PI.info(2,1).TransientTime;  rlt(3).ILMI.PI.info(1,1).TransientTime;  rlt(3).ILMI.PI.info(2,1).TransientTime],'%.1f'),...
    num2str([rlt(1).TW.PI.info(1,2).TransientTime;  rlt(1).TW.PI.info(2,2).TransientTime;  rlt(1).ILMI.PI.info(1,2).TransientTime;  rlt(1).ILMI.PI.info(2,2).TransientTime;...
             rlt(2).TW.PI.info(1,2).TransientTime;  rlt(2).TW.PI.info(2,2).TransientTime;  rlt(2).ILMI.PI.info(1,2).TransientTime;  rlt(2).ILMI.PI.info(2,2).TransientTime;...
             rlt(3).TW.PI.info(1,2).TransientTime;  rlt(3).TW.PI.info(2,2).TransientTime;  rlt(3).ILMI.PI.info(1,2).TransientTime;  rlt(3).ILMI.PI.info(2,2).TransientTime],'%.1f'),...
    num2str([rlt(1).TW.PI.info(1,3).TransientTime;  rlt(1).TW.PI.info(2,3).TransientTime;  rlt(1).ILMI.PI.info(1,3).TransientTime;  rlt(1).ILMI.PI.info(2,3).TransientTime;...
             rlt(2).TW.PI.info(1,3).TransientTime;  rlt(2).TW.PI.info(2,3).TransientTime;  rlt(2).ILMI.PI.info(1,3).TransientTime;  rlt(2).ILMI.PI.info(2,3).TransientTime;...
             rlt(3).TW.PI.info(1,3).TransientTime;  rlt(3).TW.PI.info(2,3).TransientTime;  rlt(3).ILMI.PI.info(1,3).TransientTime;  rlt(3).ILMI.PI.info(2,3).TransientTime],'%.1f'),...
    [1; 1; 2; 2;...
     3; 3; 4; 4;...
     5; 5; 6; 6]...
    );
tab3.Properties.RowNames={...
    '10^3 TW r-w_D',...
    '10^3 TW v-w_B',...
    '10^3 ILMI r-w_D',...
    '10^3 ILMI v-w_B',...
    '10^2 TW r-w_D',...
    '10^2 TW v-w_B',...
    '10^2 ILMI r-w_D',...
    '10^2 ILMI v-w_B',...
    '10 TW r-w_D',...
    '10 TW v-w_B',...
    '10 ILMI r-w_D',...
    '10 ILMI v-w_B'};
tab3.Properties.VariableNames={'ITAE w_{D,r}','ITAE w_{B,r}','ITAE f','Sett T w_{D,r}','Sett T w_{B,r}','Sett T f','#'};
tab3
save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','tab3','-append');
%--------------------------------------------------------------------------
% ----- Table 3 -----------------------------------------------------------
tab4=table(...
    num2str([rlt(1).TW.PID.info(1,1).ITAE;           rlt(1).TW.PID.info(2,1).ITAE;           rlt(1).ILMI.PID.info(1,1).ITAE;           rlt(1).ILMI.PID.info(2,1).ITAE;...
             rlt(2).TW.PID.info(1,1).ITAE;           rlt(2).TW.PID.info(2,1).ITAE;           rlt(2).ILMI.PID.info(1,1).ITAE;           rlt(2).ILMI.PID.info(2,1).ITAE;...
             rlt(3).TW.PID.info(1,1).ITAE;           rlt(3).TW.PID.info(2,1).ITAE;           rlt(3).ILMI.PID.info(1,1).ITAE;           rlt(3).ILMI.PID.info(2,1).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PID.info(1,2).ITAE;           rlt(1).TW.PID.info(2,2).ITAE;           rlt(1).ILMI.PID.info(1,2).ITAE;           rlt(1).ILMI.PID.info(2,2).ITAE;...
             rlt(2).TW.PID.info(1,2).ITAE;           rlt(2).TW.PID.info(2,2).ITAE;           rlt(2).ILMI.PID.info(1,2).ITAE;           rlt(2).ILMI.PID.info(2,2).ITAE;...
             rlt(3).TW.PID.info(1,2).ITAE;           rlt(3).TW.PID.info(2,2).ITAE;           rlt(3).ILMI.PID.info(1,2).ITAE;           rlt(3).ILMI.PID.info(2,2).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PID.info(1,3).ITAE;           rlt(1).TW.PID.info(2,3).ITAE;           rlt(1).ILMI.PID.info(1,3).ITAE;           rlt(1).ILMI.PID.info(2,3).ITAE;...
             rlt(2).TW.PID.info(1,3).ITAE;           rlt(2).TW.PID.info(2,3).ITAE;           rlt(2).ILMI.PID.info(1,3).ITAE;           rlt(2).ILMI.PID.info(2,3).ITAE;...
             rlt(3).TW.PID.info(1,3).ITAE;           rlt(3).TW.PID.info(2,3).ITAE;           rlt(3).ILMI.PID.info(1,3).ITAE;           rlt(3).ILMI.PID.info(2,3).ITAE],'%.1f'),...
    num2str([rlt(1).TW.PID.info(1,1).TransientTime;  rlt(1).TW.PID.info(2,1).TransientTime;  rlt(1).ILMI.PID.info(1,1).TransientTime;  rlt(1).ILMI.PID.info(2,1).TransientTime;...
             rlt(2).TW.PID.info(1,1).TransientTime;  rlt(2).TW.PID.info(2,1).TransientTime;  rlt(2).ILMI.PID.info(1,1).TransientTime;  rlt(2).ILMI.PID.info(2,1).TransientTime;...
             rlt(3).TW.PID.info(1,1).TransientTime;  rlt(3).TW.PID.info(2,1).TransientTime;  rlt(3).ILMI.PID.info(1,1).TransientTime;  rlt(3).ILMI.PID.info(2,1).TransientTime],'%.1f'),...
    num2str([rlt(1).TW.PID.info(1,2).TransientTime;  rlt(1).TW.PID.info(2,2).TransientTime;  rlt(1).ILMI.PID.info(1,2).TransientTime;  rlt(1).ILMI.PID.info(2,2).TransientTime;...
             rlt(2).TW.PID.info(1,2).TransientTime;  rlt(2).TW.PID.info(2,2).TransientTime;  rlt(2).ILMI.PID.info(1,2).TransientTime;  rlt(2).ILMI.PID.info(2,2).TransientTime;...
             rlt(3).TW.PID.info(1,2).TransientTime;  rlt(3).TW.PID.info(2,2).TransientTime;  rlt(3).ILMI.PID.info(1,2).TransientTime;  rlt(3).ILMI.PID.info(2,2).TransientTime],'%.1f'),...
    num2str([rlt(1).TW.PID.info(1,3).TransientTime;  rlt(1).TW.PID.info(2,3).TransientTime;  rlt(1).ILMI.PID.info(1,3).TransientTime;  rlt(1).ILMI.PID.info(2,3).TransientTime;...
             rlt(2).TW.PID.info(1,3).TransientTime;  rlt(2).TW.PID.info(2,3).TransientTime;  rlt(2).ILMI.PID.info(1,3).TransientTime;  rlt(2).ILMI.PID.info(2,3).TransientTime;...
             rlt(3).TW.PID.info(1,3).TransientTime;  rlt(3).TW.PID.info(2,3).TransientTime;  rlt(3).ILMI.PID.info(1,3).TransientTime;  rlt(3).ILMI.PID.info(2,3).TransientTime],'%.1f'),...
    [7; 7; 8; 8;...
     9; 9; 10; 10;...
     11; 11; 12; 12]...
    );
tab4.Properties.RowNames={...
    '10^3 TW r-w_D',...
    '10^3 TW v-w_B',...
    '10^3 ILMI r-w_D',...
    '10^3 ILMI v-w_B',...
    '10^2 TW r-w_D',...
    '10^2 TW v-w_B',...
    '10^2 ILMI r-w_D',...
    '10^2 ILMI v-w_B',...
    '10 TW r-w_D',...
    '10 TW v-w_B',...
    '10 ILMI r-w_D',...
    '10 ILMI v-w_B'};
tab4.Properties.VariableNames={'ITAE w_{D,r}','ITAE w_{B,r}','ITAE f','Sett T w_{D,r}','Sett T w_{B,r}','Sett T f','#'};
tab4
save('cases\WoodBerry\lmilab\results\data\lmilab_exWB_tb_rlt.mat','tab4','-append');